const products = [
    // Frutas y Verduras
    { id: 1, name: 'Plátano orgánico', price: 1.50, image: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=300&h=200&q=80', category: 'Frutas y Verduras', featured: true, description: 'Plátanos orgánicos, dulces y llenos de potasio.' },
    { id: 2, name: 'Manzana', price: 2.10, image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?auto=format&fit=crop&w=300&h=200&q=80', category: 'Frutas y Verduras', featured: false, description: 'Manzanas rojas crujientes, perfectas para cualquier momento.' },
    { id: 3, name: 'Palta', price: 4.50, image: 'https://jumboargentina.vtexassets.com/arquivos/ids/448302/Palta-Hass-Premium-Por-Unidad-1-29308.jpg?v=636562507417630000', category: 'Frutas y Verduras', featured: true, description: 'Palta Hass cremosa, ideal para tus desayunos y ensaladas.' },
    { id: 4, name: 'Zanahoria', price: 1.20, image: 'https://images.unsplash.com/photo-1590868309235-ea34bed7bd7f?auto=format&fit=crop&w=300&h=200&q=80', category: 'Frutas y Verduras', featured: false, description: 'Zanahorias frescas y orgánicas, ricas en vitamina A.' },
    { id: 5, name: 'Espinaca', price: 2.00, image: 'https://www.seednative.es/fotky7292/fotos/_vyr_787invieno.jpg', category: 'Frutas y Verduras', featured: false, description: 'Hojas de espinaca tiernas, fuente de hierro y nutrientes.' },
    { id: 6, name: 'Tomate', price: 1.80, image: 'https://www.diosafruit.com/assets/files/tomaten-products-diosa-fruit.480x0.jpg', category: 'Frutas y Verduras', featured: false, description: 'Tomates jugosos para salsas o ensaladas frescas.' },
    { id: 7, name: 'Lechuga', price: 1.30, image: 'https://ceagesp.gov.br/wp-content/uploads/2020/05/alface-619x464.jpg', category: 'Frutas y Verduras', featured: false, description: 'Lechuga romana crujiente, la base de una ensalada César perfecta.' },
    { id: 8, name: 'Brócoli', price: 2.50, image: 'https://www.centarzdravlja.hr/site/assets/files/6217/brokula2.jpg', category: 'Frutas y Verduras', featured: false, description: 'Brócoli fresco, lleno de vitaminas y minerales.' },
    { id: 9, name: 'Naranja', price: 2.20, image: 'https://www.fluentu.com/blog/wp-content/uploads/site/3/fruits-in-french-9.jpg', category: 'Frutas y Verduras', featured: false, description: 'Naranjas jugosas, ideales para un zumo matutino.' },
    { id: 10, name: 'Mango', price: 3.50, image: 'https://images.freshop.com/7777369/27b428bf2b6255576d31db8127b3194c_large.png', category: 'Frutas y Verduras', featured: false, description: 'Mango Kent dulce y sin hebras, un manjar tropical.' },
    // Granos y Legumbres
    { id: 11, name: 'Quinua blanca', price: 5.50, image: 'https://mmpp.cl/wp-content/uploads/2024/06/Photoroom_20240611_142654-510x510.jpg', category: 'Granos y Legumbres', featured: true, description: 'Quinua blanca orgánica, una superfood llena de proteínas.' },
    { id: 12, name: 'Lenteja', price: 3.20, image: 'https://tienda.frutaseloy.com/wp-content/uploads/2024/02/lenteja_castellana.png', category: 'Granos y Legumbres', featured: false, description: 'Lentejas de la sierra, perfectas para guisos y sopas.' },
    { id: 13, name: 'Frijol canario', price: 3.00, image: 'https://tse3.mm.bing.net/th/id/OIP.jfdLJbolKhuWapthM-2owQHaE8?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3', category: 'Granos y Legumbres', featured: false, description: 'Frijol canario cremoso, un clásico de la cocina.' },
    { id: 14, name: 'Garbanzo', price: 2.80, image: 'https://vegetalesyfrutas.cl/wp-content/uploads/2021/05/garbanzos-copia.webp', category: 'Granos y Legumbres', featured: false, description: 'Garbanzos para hummus, ensaladas o potajes.' },
    { id: 15, name: 'Arroz integral', price: 4.00, image: 'https://global.cdn.magazord.com.br/bancadonando/img/2023/08/produto/1219/arroz-agulha-integral.png?ims=fit-in/600x600/filters:fill(white)', category: 'Granos y Legumbres', featured: false, description: 'Arroz integral, una opción saludable y rica en fibra.' },
    { id: 16, name: 'Avena orgánica', price: 3.80, image: 'https://v.wpimg.pl/MDA0MTU5YiUgUjtnek5vMGMKbz08F2FmNBJ3dnp6YnJ1BDVgZgViIG9HPT04UmM0LR98Z2QGe3ZxAH9meBh-c3cDemJnDXxrcgF8YmINeHUeXGM-JVJvOQ', category: 'Granos y Legumbres', featured: false, description: 'Avena en hojuelas para un desayuno energético.' },
    { id: 17, name: 'Chía', price: 6.00, image: 'https://imag.bonviveur.com/semillas-de-chia-al-natural.jpg', category: 'Granos y Legumbres', featured: false, description: 'Semillas de chía, ricas en omega-3 y fibra.' },
    { id: 18, name: 'Soya en grano', price: 3.50, image: 'https://tse1.mm.bing.net/th/id/OIP.bgn0Os_0UMM3NCaLNusnoAHaEF?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3', category: 'Granos y Legumbres', featured: false, description: 'Soya en grano para preparar leche o tofu casero.' },
    // Productos Procesados Naturales
    { id: 19, name: 'Miel de abeja pura', price: 8.00, image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?auto=format&fit=crop&w=300&h=200&q=80', category: 'Procesados Naturales', featured: true, description: 'Miel de abeja 100% pura, sin aditivos.' },
    { id: 20, name: 'Aceite de coco', price: 12.00, image: 'https://e7.pngegg.com/pngimages/121/390/png-clipart-coconut-oil-food-cooking-oils-coco-cream-food.png', category: 'Procesados Naturales', featured: false, description: 'Aceite de coco prensado en frío, ideal para cocinar o para el cuidado personal.' },
    { id: 21, name: 'Mermelada de fresa', price: 6.50, image: 'https://tse4.mm.bing.net/th/id/OIP.1LVIjYOVKm0_z-CNR5BLnwHaHa?cb=12&w=2048&h=2048&rs=1&pid=ImgDetMain&o=7&rm=3', category: 'Procesados Naturales', featured: false, description: 'Mermelada casera de fresa, endulzada naturalmente.' },
    { id: 22, name: 'Pan integral artesanal', price: 5.00, image: 'https://images.unsplash.com/photo-1534620808146-d33bb39128b2?auto=format&fit=crop&w=300&h=200&q=80', category: 'Procesados Naturales', featured: true, description: 'Pan integral hecho con masa madre y harinas orgánicas.' },
    // Infusiones 
    { id: 23, name: 'Manzanilla', price: 4.00, image: 'https://www.tiendamika.cl/cdn/shop/products/13MANZANILLA1_480x480.png?v=1654160337', category: 'Infusiones y Superfoods', featured: false, description: 'Infusión digestiva de muña andina.' },
    { id: 24, name: 'Maca en polvo', price: 9.00, image: 'https://tse1.mm.bing.net/th/id/OIP.TGZSNFp3gOe8gxLKfvo7OQHaHa?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3', category: 'Infusiones y Superfoods', featured: true, description: 'Maca en polvo para un extra de energía y vitalidad.' },
    // Higiene y Cuidado Personal
    { id: 25, name: 'Jabón artesanal de avena', price: 5.50, image: 'https://mejorconsalud.as.com/wp-content/uploads/2017/10/jabon-artesanal-avena.jpg', category: 'Higiene y Cuidado Personal', featured: false, description: 'Jabón suave y exfoliante con avena natural.' },
    { id: 26, name: 'Shampoo sólido de romero', price: 10.00, image: 'https://cdn2.cocinadelirante.com/sites/default/files/styles/gallerie/public/shampoo-solido-de-romero-champu.jpg', category: 'Higiene y Cuidado Personal', featured: true, description: 'Shampoo sólido ecológico para fortalecer el cabello.' },
];